on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      actions: write
    name: Build (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
          - os: ubuntu-latest
            target: aarch64-linux
            package: aarch64-linux
          - os: macos-latest
            target: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: cachix/cachix-action@v15
        with:
          name: bombadil
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix config show
      - run: nix flake check .
      - name: Build package
        run: nix build .#${{ matrix.package || 'default' }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: bombadil-${{ matrix.target }}
          path: result/bin/bombadil
      - name: Build Docker image
        if: matrix.target == 'x86_64-linux'
        run: nix build ".#docker"

  manual:
    permissions:
      contents: read
    name: Build Manual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: cachix/cachix-action@v15
        with:
          name: bombadil
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix config show
      - run: nix build ".#manual"
      - name: Upload manual
        uses: actions/upload-artifact@v4
        with:
          name: bombadil-manual.zip
          path: result/
